import Foundation

public struct MigrationV009: Migration {
    public let version: SchemaVersion = .v9
    public let description = "Enforce same-company ownership across referenced records"

    public init() {}

    public func up(_ db: SQLiteDatabase) throws {
        let triggers: [String] = [
            ownershipTrigger(name: "trg_avelo_groups_parent_company_insert", timing: "INSERT", table: "avelo_account_groups", oldOrNew: "NEW", check: "NEW.parent_group_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_account_groups g WHERE g.id = NEW.parent_group_id AND g.company_id = NEW.company_id)", message: "Parent group must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_groups_parent_company_update", timing: "UPDATE", table: "avelo_account_groups", oldOrNew: "NEW", check: "NEW.parent_group_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_account_groups g WHERE g.id = NEW.parent_group_id AND g.company_id = NEW.company_id)", message: "Parent group must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_accounts_group_company_insert", timing: "INSERT", table: "avelo_accounts", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_account_groups g WHERE g.id = NEW.group_id AND g.company_id = NEW.company_id)", message: "Account group must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_accounts_group_company_update", timing: "UPDATE", table: "avelo_accounts", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_account_groups g WHERE g.id = NEW.group_id AND g.company_id = NEW.company_id)", message: "Account group must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_sequences_fy_company_insert", timing: "INSERT", table: "avelo_voucher_sequences", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_financial_years fy WHERE fy.id = NEW.financial_year_id AND fy.company_id = NEW.company_id)", message: "Voucher sequence financial year must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_sequences_fy_company_update", timing: "UPDATE", table: "avelo_voucher_sequences", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_financial_years fy WHERE fy.id = NEW.financial_year_id AND fy.company_id = NEW.company_id)", message: "Voucher sequence financial year must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_vouchers_company_insert", timing: "INSERT", table: "avelo_vouchers", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_financial_years fy WHERE fy.id = NEW.financial_year_id AND fy.company_id = NEW.company_id) OR (NEW.party_account_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.party_account_id AND a.company_id = NEW.company_id))", message: "Voucher references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_vouchers_company_update", timing: "UPDATE", table: "avelo_vouchers", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_financial_years fy WHERE fy.id = NEW.financial_year_id AND fy.company_id = NEW.company_id) OR (NEW.party_account_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.party_account_id AND a.company_id = NEW.company_id))", message: "Voucher references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_lines_company_insert", timing: "INSERT", table: "avelo_ledger_lines", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.account_id AND a.company_id = NEW.company_id)", message: "Ledger-line voucher and account must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_lines_company_update", timing: "UPDATE", table: "avelo_ledger_lines", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.account_id AND a.company_id = NEW.company_id)", message: "Ledger-line voucher and account must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_movements_company_insert", timing: "INSERT", table: "avelo_stock_movements", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_inventory_items i WHERE i.id = NEW.item_id AND i.company_id = NEW.company_id) OR (NEW.voucher_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id)) OR (NEW.reversed_movement_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_stock_movements m WHERE m.id = NEW.reversed_movement_id AND m.company_id = NEW.company_id))", message: "Stock movement references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_movements_company_update", timing: "UPDATE", table: "avelo_stock_movements", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_inventory_items i WHERE i.id = NEW.item_id AND i.company_id = NEW.company_id) OR (NEW.voucher_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id)) OR (NEW.reversed_movement_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_stock_movements m WHERE m.id = NEW.reversed_movement_id AND m.company_id = NEW.company_id))", message: "Stock movement references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_payroll_employees_company_insert", timing: "INSERT", table: "avelo_payroll_employees", oldOrNew: "NEW", check: "NEW.bank_account_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.bank_account_id AND a.company_id = NEW.company_id)", message: "Payroll employee bank account must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_payroll_employees_company_update", timing: "UPDATE", table: "avelo_payroll_employees", oldOrNew: "NEW", check: "NEW.bank_account_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.bank_account_id AND a.company_id = NEW.company_id)", message: "Payroll employee bank account must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_payroll_entries_company_insert", timing: "INSERT", table: "avelo_payroll_entries", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_payroll_employees e WHERE e.id = NEW.employee_id AND e.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_financial_years fy WHERE fy.id = NEW.financial_year_id AND fy.company_id = NEW.company_id) OR (NEW.voucher_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id))", message: "Payroll entry references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_payroll_entries_company_update", timing: "UPDATE", table: "avelo_payroll_entries", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_payroll_employees e WHERE e.id = NEW.employee_id AND e.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_financial_years fy WHERE fy.id = NEW.financial_year_id AND fy.company_id = NEW.company_id) OR (NEW.voucher_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id))", message: "Payroll entry references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_orders_company_insert", timing: "INSERT", table: "avelo_inventory_orders", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.party_account_id AND a.company_id = NEW.company_id)", message: "Inventory order party must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_orders_company_update", timing: "UPDATE", table: "avelo_inventory_orders", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.party_account_id AND a.company_id = NEW.company_id)", message: "Inventory order party must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_order_lines_company_insert", timing: "INSERT", table: "avelo_inventory_order_lines", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_inventory_orders o WHERE o.id = NEW.order_id AND o.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_inventory_items i WHERE i.id = NEW.item_id AND i.company_id = NEW.company_id)", message: "Inventory order-line references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_order_lines_company_update", timing: "UPDATE", table: "avelo_inventory_order_lines", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_inventory_orders o WHERE o.id = NEW.order_id AND o.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_inventory_items i WHERE i.id = NEW.item_id AND i.company_id = NEW.company_id)", message: "Inventory order-line references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_reorder_levels_company_insert", timing: "INSERT", table: "avelo_inventory_reorder_levels", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_inventory_items i WHERE i.id = NEW.item_id AND i.company_id = NEW.company_id)", message: "Inventory reorder item must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_reorder_levels_company_update", timing: "UPDATE", table: "avelo_inventory_reorder_levels", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_inventory_items i WHERE i.id = NEW.item_id AND i.company_id = NEW.company_id)", message: "Inventory reorder item must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_bank_recon_company_insert", timing: "INSERT", table: "avelo_bank_reconciliations", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.bank_account_id AND a.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id)", message: "Bank reconciliation references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_bank_recon_company_update", timing: "UPDATE", table: "avelo_bank_reconciliations", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.bank_account_id AND a.company_id = NEW.company_id) OR NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.voucher_id AND v.company_id = NEW.company_id)", message: "Bank reconciliation references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_bank_statement_company_insert", timing: "INSERT", table: "avelo_bank_statement_lines", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.bank_account_id AND a.company_id = NEW.company_id) OR (NEW.matched_voucher_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.matched_voucher_id AND v.company_id = NEW.company_id))", message: "Bank statement references must belong to the same company."),
            ownershipTrigger(name: "trg_avelo_bank_statement_company_update", timing: "UPDATE", table: "avelo_bank_statement_lines", oldOrNew: "NEW", check: "NOT EXISTS (SELECT 1 FROM avelo_accounts a WHERE a.id = NEW.bank_account_id AND a.company_id = NEW.company_id) OR (NEW.matched_voucher_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM avelo_vouchers v WHERE v.id = NEW.matched_voucher_id AND v.company_id = NEW.company_id))", message: "Bank statement references must belong to the same company.")
        ]

        for trigger in triggers {
            try db.execute(trigger)
        }
    }

    private func ownershipTrigger(name: String,
                                  timing: String,
                                  table: String,
                                  oldOrNew: String,
                                  check: String,
                                  message: String) -> String {
        """
        CREATE TRIGGER IF NOT EXISTS \(name)
        BEFORE \(timing) ON \(table)
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, '\(message)')
            WHERE \(check);
        END;
        """
    }
}
